site_name: PCGO
theme:
    name: material
    palette:
        primary: custom
    font:
        text: Roboto
    logo: assets/logo.png
    features:
        - content.code.annotate
        - content.tabs.link
        - header.autohide
        - navigation.instant
        - navigation.sections
        - navigation.tabs
        - navigation.top
        - navigation.tracking

nav:
    - Sobre: index.md
    - Guias:
        - Guia de Contribuição: guia_de_contribuicao.md
        - Guia de Estilo: guia_de_estilo.md
        - Protótipo: prototipo_alta_fidelidade.md
    - Comunicação:
        - Rituais da Equipe:  rituais.md
        - Codigo de Conduta: codigo_conduta.md
        - Relatório de Eventos: 
            - Semana 1: Relatórios/semana1.md
            - Semana 2: Relatórios/semana2.md
            - Semana 3: Relatórios/semana3.md
            - Semana 4: Relatórios/semana4.md
    - Planejamento:
        - Planejamento: planejamento.md
        - Quadro de conhecimento: Controle/quadro_de_conhecimento.md
        - Quadro de disponibilidade: Controle/quadro_de_disponibilidade.md
        - Cronograma de dojo: Controle/cronograma_de_dojo.md
    - Planos:
        - Plano de custos: Planos/plano_de_custos.md
        - Plano de riscos: Planos/plano_de_riscos.md
    - Definições do Projeto:
        - Metodologias: DefiniçõesDoProjeto/metodologia.md
        - Plano de qualidade: Planos/plano_de_qualidade.md
        - Plano de comunicacao: Planos/plano_de_comunicacao.md
    - Gestão de Projeto:
        - EAP (Estrutura Analítica do Projeto): GestaoProjeto/eap.md
    - Lean Inception:
        - Dinamicas: Lean/Dinamicas/dinamicas.md
        - Visão do Produto: Lean/visão_do_produto.md
        - É, não é, faz, não faz: Lean/e_naoe_faz_naofaz.md
        - Sequenciador: Lean/sequenciador.md
        - Canvas MVP: Lean/mvp_canvas.md
        - Brainstoming: Lean/brainstorming_funcionalidades.md
        - Jornadas: Lean/jornadas.md
        - Objetivos de negócio: Lean/objetivos_de_negocio.md
        - Personas: Lean/personas.md
    - Arquitetura:
        - Documento de arquitetura: Arquitetura/documentoArquitetura.md
        - Printer Service: Arquitetura/PrinterService.md
        - Estimativa de dias: Lean/estimativa_de_dias.md
    - Relatório de Encerramento do Projeto: Relatórios/relatorio_encerramento_projeto.md

extra_css:
  - stylesheets/extra.css
